### ISSUE TITLE
~/.vim/session 에 파일이 없을 때 발생하는 에러

### ISSUE THREAD

**Issue by dveamer** [johngrib/fav-dir#1]
fav를 이용해서 이동시에 아래와 같은 메시지가 출력되고 있습니다.

~~~terminal
$ fav
grep: ~/.vim/session/*: 그런 파일이나 디렉터리가 없습니다
~~~

```~/.vim/session/``` 디렉토리 아래에 파일이 존재하지 않을 때 발생하는 것으로 보이고 임의의 파일을 만들어두니 정상적으로 이동하는 것을 확인했습니다.

**Comment by johngrib** [comment]
제보 감사합니다!
